### ISSUE TITLE
Where the save language ini option save the file?

### ISSUE THREAD

**Issue by ghost** [hrydgard/ppsspp-lang#654]
How it works?

**Comment by natuschaos** [comment]
I'm not good at finding missing strings like the new that display at boot of games "Loading modules" so I wanted to use this tool.

**Comment by vnctdj** [comment]
I've written a small tool a while ago to automatically add new strings that are missing in all .ini files.
So I can do this in a fraction of a second, you most likely have seen this in my previous commits.
However it's currently not very user-friendly. This will still needs some work.

I'm thinking about linking my tool to git in order to automate it further, so all .ini files would always be up-to-date.

However I'm currently very busy at the time (exams...) so this will have to wait for something like a month :)

**Comment by natuschaos** [comment]
Take your time @vnctdj.

**Comment by vnctdj** [comment]
While my tool is not fully automated, it allows me to update and clean (trimming unwanted spaces and natural sort) all .ini files in a few seconds.
But I won't stop enhancing it, be sure of that! :)
